baseurl = "https://www.bert-riffelmacher.de"
title = "bert riffelmacher"
theme = "hugo-coder"
languagecode = "en-en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

avatarurl = "/images/av2_bw.jpg"
#disqusShortname = "yourdiscussshortname"

[[module.mounts]]
    source = "static/images/"
    target = "assets/images/"

[params]
    author = "Bert Riffelmacher"
    info = "Computer Science, Math & Photography"
    description = "Bert Riffelmacher's blog and website"
    keywords = "blog,developer,personal"
    avatarurl = "images/av2_bw.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "“Science works!”"

    hidecredits = false
    hidecopyright = false

    rtl = false
    # katex = true # maybe for katex
    math = true
    custom_css = ["css/custom.css"]
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/sotsoguk/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 2
    url = "https://twitter.com/sotsoguk/"

# [[params.social]]
#     name = "Hackerrank"
#     icon = "fa fa-hackerrank"
#     weight = 3
#     url = "https://www.hackerrank.com/sotsoguk"
    
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 5
    url = "https://www.instagram.com/sotsoguk/"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"

[[menu.main]]
    name = "Setup"
    weight = 2
    url ="/setup/"

[[menu.main]]
    name = "CV"
    weight = 3
    url = "/files/cv.pdf"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


[markup]
    [markup.highlight]
        lineNos = true
        style = "monokai"
        codeFences = true
        anchorLineNos = false